ERM.Musicas.Web/Controllers/AlbunsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ERM.Musicas.AcessoDados.Entity.Context;
using ERM.Musicas.Dominio;
using AutoMapper;
using ERM.Musicas.Web.ViewModels.Album;
using ERM.Repositorio.Comum;
using ERM.Musicas.Repositorio.Entity;
using ERM.Musicas.Web.Filtros;

namespace ERM.Musicas.Web.Controllers
{
    [Authorize]
    public class AlbunsController : Controller
    {
        private IRepositorioGenerioco < Album, int> repositorioAlbuns = new AlbunsRepositorio ( new MusicasDbContext() );

        
        // GET: Albuns
        [LogActionFilter]
        public ActionResult Index()
        {
            return View(Mapper.Map<List<Album>, List<AlbumShowViewModel> >( repositorioAlbuns.Selecionar() ));
        }

        public ActionResult FiltrarByNome(string pesquisa)
        {
            List<Album> albuns = repositorioAlbuns.Selecionar().Where(a => a.Nome.Contains(pesquisa)).ToList();
            List<AlbumShowViewModel> viewModels = Mapper.Map<List<Album>,List<AlbumShowViewModel> > (albuns);
            return Json(viewModels,JsonRequestBehavior.AllowGet);
        }

        // GET: Albuns/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Album album = repositorioAlbuns.SelecionarPorId(id.Value);
            if (album == null)
            {
                return HttpNotFound();
            }
            return View(Mapper.Map<Album,AlbumShowViewModel>(album));
        }

        // GET: Albuns/Create
        [Authorize(Roles ="ADMINISTRADOR")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Albuns/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "ADMINISTRADOR")]
        public ActionResult Create([Bind(Include = "Id,Nome,Ano,Observacoes,Email")] AlbumViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                Album album = Mapper.Map<AlbumViewModel, Album>(viewModel);
                repositorioAlbuns.Inserir(album);
                return RedirectToAction("Index");
            }

            return View(viewModel);
        }

        // GET: Albuns/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Album album = repositorioAlbuns.SelecionarPorId(id.Value);
            if (album == null)
            {
                return HttpNotFound();
            }
            return View( Mapper.Map<Album,AlbumViewModel>(album) );
        }

        // POST: Albuns/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nome,Ano,Observacoes,Email")] AlbumViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                Album album = Mapper.Map<AlbumViewModel, Album>(viewModel);
                repositorioAlbuns.Alterar(album);
                return RedirectToAction("Index");
            }
            return View(viewModel);
        }

        // GET: Albuns/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Album album = repositorioAlbuns.SelecionarPorId(id.Value);
            if (album == null)
            {
                return HttpNotFound();
            }
            return View(Mapper.Map<Album,AlbumShowViewModel>(album));
        }

        // POST: Albuns/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            repositorioAlbuns.ExcluirById(id);
            return RedirectToAction("Index");
        }
    }
}

ERM.Musicas.Web/Views/Albuns/Create.cshtml
@model ERM.Musicas.Web.ViewModels.Album.AlbumViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Album</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ano, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ano, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ano, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Observacoes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Observacoes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Observacoes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ERM.Musicas.Web/Views/Albuns/Delete.cshtml
@model ERM.Musicas.Web.ViewModels.Album.AlbumShowViewModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Album</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ano)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ano)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Observacoes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Observacoes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ERM.Musicas.Web/Views/Albuns/Details.cshtml
@model ERM.Musicas.Web.ViewModels.Album.AlbumShowViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Album</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ano)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ano)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Observacoes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Observacoes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ERM.Musicas.Web/Views/Albuns/Edit.cshtml
@model ERM.Musicas.Web.ViewModels.Album.AlbumViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Album</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ano, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ano, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ano, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Observacoes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Observacoes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Observacoes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ERM.Musicas.Web/Views/Albuns/Index.cshtml
@model IEnumerable<ERM.Musicas.Web.ViewModels.Album.AlbumShowViewModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<div class="row">
    <div class="col-md-10 col-sm-10 col-lg-10">
        <input type="text" id="pesquisaAlbum" class="form-control" />
    </div>
    <div class=" col-md-2 col-sm-2 col-lg-2">
        <button id="btnPesquisaAlbum" class="btn btn-default" >Pesquisar</button>
    </div>
</div>
<table class="table" id="tblAlbuns">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ano)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Observacoes)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Ano)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Observacoes)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.Partial("_Links", item)
                </td>
            </tr>
        }
    </tbody>

</table>

@section Scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            $("#btnPesquisaAlbum").click(function () {
                var termoPesquisa = $("#pesquisaAlbum").val();
                $.ajax({
                    method: "GET",
                    url: "/Albuns/PesquisaByNome/" + termoPesquisa,
                    success: function (data) {
                        $("#tblAlbuns tbody > tr").remove();
                        $.each(data, function (i, album) {
                            $("#tblAlbuns tbody").append(
                                "<tr>" +
                                " <td>" + album.Nome + "</td>" +
                                " <td>" + album.Ano + "</td>" +
                                " <td>" + album.Observacoes + "</td>" +
                                " <td>" + album.Email + "</td>" +
                                " <td>" +
                                    "<a href= '/Albuns/Edit/" + album.Id + "'>Editar</a>" + " | "+
                                    "<a href= '/Albuns/Details/" + album.Id + "'>Detalhes</a>" +" | "+
                                    "<a href= '/Albuns/Delete/" + album.Id + "'>Deletar</a>" +
                                "</td>" +
                                "</tr>"
                            );
                        });
                    },
                    error: function (data) {
                        alert("Erro na pesquisa");
                    }
                });
            });
        });
    </script>

}

ERM.Musicas.Web/Views/Albuns/_Links.cshtml
@model ERM.Musicas.Web.ViewModels.Album.AlbumShowViewModel

@Html.ActionLink("Details", "Details", new { id = Model.Id }) |
@if (User.IsInRole("ADMINISTRADOR"))
{
    <a href="@Url.Action("Edit","Albuns")">Edit | </a>
    <a href = "@Url.Action("Delete","Albuns")" >Delete</a > 
}